#!/usr/bin/with-contenv bash
# shellcheck shell=bash

cd /app || exit

crontab -r

echo "${CRON} bash /app/sync_emby_config.sh ${EMBY} ${RESILIO} >> /config/cron.log 2>&1" > /app/cronjob.list
echo "bash /app/sync_emby_config.sh ${EMBY} ${RESILIO}" > /app/command.sh

if crontab /app/cronjob.list; then
    echo "定时任务添加成功"
else
    echo "定时任务添加失败"
    exit 1
fi