#!/usr/bin/with-contenv bash
# shellcheck shell=bash

Green="\033[32m"
Red="\033[31m"
Yellow='\033[33m'
Font="\033[0m"
INFO="[${Green}INFO${Font}]"
ERROR="[${Red}ERROR${Font}]"
WARN="[${Yellow}WARN${Font}]"
function INFO() {
    echo -e "${INFO} ${1}"
}
function ERROR() {
    echo -e "${ERROR} ${1}"
}
function WARN() {
    echo -e "${WARN} ${1}"
}

if [ ! -d /app ]; then
    mkdir /app
fi
cd /app || exit

crontab -r

CRON_COMMAND="bash -c \"\$(curl http://docker.xiaoya.pro/sync_emby_config.sh)\" -s ${HOST_MEDIA_DIR} ${HOST_CONFIG_DIR} ${EMBY} ${RESILIO}"

echo -e "${CRON} ${CRON_COMMAND} >> ${HOST_RESILIO_DIR}/cron.log 2>&1" > /app/cronjob.list
echo -e "${CRON_COMMAND}" > /app/command.sh

INFO "$(cat /app/cronjob.list)"

if crontab /app/cronjob.list; then
    INFO "定时任务添加成功"
else
    ERROR "定时任务添加失败"
    exit 1
fi