name: emby metadata downloader

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - "emby_metadata_downloader/**"
      - ".github/workflows/build_emby_metadata_downloader.yml"

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build Docker Image
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ secrets.DOCKER_USERNAME }}/xiaoya-emd
          tags: |
            type=raw,value=latest

      -
        name: Set Up QEMU
        uses: docker/setup-qemu-action@v3

      -
        name: Set Up Buildx
        uses: docker/setup-buildx-action@v3

      -
        name: Login DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      -
        name: Build Image
        uses: docker/build-push-action@v6
        with:
          context: ./emby_metadata_downloader
          file: emby_metadata_downloader/Dockerfile
          platforms: |
            linux/amd64
            linux/arm64/v8
            linux/arm/v7
          build-args: |
            BRANCH=main
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - 
        name: Docker Hub Description
        uses: peter-evans/dockerhub-description@v4
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: ${{ secrets.DOCKER_USERNAME }}/xiaoya-emd
          short-description: 小雅Alist的相关周边
          readme-filepath: ./emby_metadata_downloader/README.md

  Windows-amd64:
    runs-on: windows-latest
    name: Build Windows Binary
    steps:
      - 
        name: Checkout
        uses: actions/checkout@v4

      - 
        name: Init Python 3.12
        uses: actions/setup-python@v5
        with:
            python-version: '3.12'
            cache: 'pip'

      - 
        name: Install Dependent Packages
        run: |
            git clone -b main https://github.com/Rik-F5/xiaoya_db.git xiaoya_db
            copy xiaoya_db/requirements.txt requirements.txt
            copy xiaoya_db/solid.py solid.py
            python -m pip install --upgrade pip
            pip install wheel pyinstaller
            pip install -r requirements.txt
        shell: pwsh
        working-directory: ./emby_metadata_downloader

      - 
        name: Pyinstaller
        run: |
            pyinstaller solid.spec
        working-directory: ./emby_metadata_downloader
        shell: pwsh

      - 
        name: Upload Windows File
        uses: actions/upload-artifact@v3
        with:
            name: solid-windows-amd64
            path: emby_metadata_downloader/dist/solid.exe

  Update:
    runs-on: ubuntu-latest
    needs: [ Windows-amd64, build ]
    steps:
      - 
        name: Checkout
        uses: actions/checkout@v4

      - 
        name: Download Artifact
        uses: actions/download-artifact@v3

      - 
        name: Rename
        shell: bash
        run: |
            mv ./solid-windows-amd64/solid.exe ./emby_metadata_downloader/solid-windows-amd64.exe

      - 
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
            commit_message: 'chore: update solid windows exe'
            branch: master
            file_pattern: './emby_metadata_downloader/solid-windows-amd64.exe'
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
